src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message:"Veuillez saisir une adresse email")]
    #[Assert\Length(max : 180)]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    private ?string $plainPassword = null;

    #[ORM\Column(length: 30)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min : 3,
        max : 30
    )]
    private ?string $username = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column]
    private ?bool $is_enabled = true;

    #[ORM\ManyToMany(targetEntity: Product::class)]
    private Collection $products;

    #[ORM\ManyToMany(targetEntity: Address::class, inversedBy: 'users', cascade:["persist"])]
    private Collection $Addresses;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Store::class)]
    private Collection $ownedStores;

    #[ORM\ManyToMany(targetEntity: Store::class, inversedBy: 'favouritesUsers')]
    private Collection $favourites;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->Addresses = new ArrayCollection();
        $this->ownedStores = new ArrayCollection();
        $this->favourites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
         //$this->plainPassword = null;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function isIsEnabled(): ?bool
    {
        return $this->is_enabled;
    }

    public function setIsEnabled(bool $is_enabled): self
    {
        $this->is_enabled = $is_enabled;

        return $this;
    }


    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        $this->products->removeElement($product);

        return $this;
    }

    /**
     * @return Collection<int, Address>
     */
    public function getAddresses(): Collection
    {
        return $this->Addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->Addresses->contains($address)) {
            $this->Addresses->add($address);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        $this->Addresses->removeElement($address);

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Store>
     */
    public function getOwnedStores(): Collection
    {
        return $this->ownedStores;
    }

    public function addOwnedStore(Store $ownedStore): self
    {
        if (!$this->ownedStores->contains($ownedStore)) {
            $this->ownedStores->add($ownedStore);
            $ownedStore->setOwner($this);
        }

        return $this;
    }

    public function removeOwnedStore(Store $ownedStore): self
    {
        if ($this->ownedStores->removeElement($ownedStore)) {
            // set the owning side to null (unless already changed)
            if ($ownedStore->getOwner() === $this) {
                $ownedStore->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Store>
     */
    public function getFavourites(): Collection
    {
        return $this->favourites;
    }

    public function addFavourite(Store $favourite): self
    {
        if (!$this->favourites->contains($favourite)) {
            $this->favourites->add($favourite);
        }

        return $this;
    }

    public function removeFavourite(Store $favourite): self
    {
        $this->favourites->removeElement($favourite);

        return $this;
    }

    public function __toString()
    {
        return $this->getUsername();
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\PropertyAccess\PropertyAccess;
use App\Entity\User;
use App\Entity\Store;
use App\Entity\Product;
use App\Form\EditProfileType;
use App\Repository\AddressRepository;
use App\Repository\UserRepository;
use App\Repository\StoreRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

#[Route('', name: 'user_')]
class UserController extends AbstractController
{
    public function __construct(private UserRepository $userRepository)
    {

    }

    #[Route('/login', name: 'login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if user is already connected :
        /*    if ($this->getUser()) {
            return $this->redirectToRoute('main_index');
        }*/
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('user/login.html.twig', [
            'lastUsername' => $lastUsername,
            'error' => $error,
        ]);
    }

    //Get and set User favourites stores
    #[Route('/favorite', name: 'favorite')]
    #[IsGranted('ROLE_USER')]
    public function favorite(): Response
    {
        $getFavorites = $this->getUser()->getFavourites()->getValues();

        return $this->render('user/favorite.html.twig', [
    "favoritesList" => $getFavorites]);

    }

    #[Route('/grocery-list', name: 'grocery-list')]
    #[IsGranted('ROLE_USER')]
    public function groceryList(): Response
    {

        $GroceriesList = $this->getUser()->getProducts()->getValues();


        return $this->render('user/grocery-list.html.twig', [
            'groceryList' => $GroceriesList
        ]);
    }

    #[Route('/remove-product/{id}', name: 'remove-product')]
    #[IsGranted('ROLE_USER')]
    public function removeProduct(Request $request, EntityManagerInterface $em, ProductRepository $productRepository, Product $product): Response
    {

        $productId = $product->getId();
        $user = $this->getUser();
        $user->removeProduct(
            $productRepository->find($productId)
        );

        $em->flush();   

        return $this->redirect($request->headers->get('referer'));

    }

    #[Route('/profil-client', name: 'profil-client')]
    public function profilClient(): Response
    {
        $userInfo = $this->getUser();

        return $this->render('user/profil-client.html.twig', [
            'user' => $userInfo,
        ]);
    }

    #[Route('/profile-edit', name: 'profile-edit')]
    #[IsGranted('ROLE_USER')]
    public function editProfile(
        Request $request,
        EntityManagerInterface $em
    ): Response {

        $userInfo = $this->getUser();


        $form = $this->createForm(EditProfileType::class, $userInfo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
        
            $em->persist($userInfo);
            $em->flush();

            if ($this->isGranted('ROLE_PRODUCER')) {
            return $this->redirectToRoute('user_profil-pro');
            }
            else {

                return $this->redirectToRoute('user_profil-client');
            }
        }

    return $this->render('user/profil-client-edit.html.twig', [
        'user' => $userInfo,
        'formEdit' => $form->createView(),
    ]);
}


    #[Route('/remove/favorite/{id}', name: 'remove_favorite')]
    #[IsGranted('ROLE_USER')]
    public function removeFavorite(Request $request, StoreRepository $storeRepository, EntityManagerInterface $em, Store $store): Response
    {
        $storeId = $store->getId();
        $user = $this->getUser();
        $user->RemoveFavourite(
            $storeRepository->find($storeId)
        );
        $em->flush();   

        return $this->redirect($request->headers->get('referer'));

    }

    #[Route('/profil-pro', name: 'profil-pro')]
    #[IsGranted('ROLE_PRODUCER')]
    public function profilPro(): Response
    {
        $user = $this->getUser();
        return $this->render('user/profil-pro.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route(path: '/logout', name: 'logout')]
    public function logout(): void
    {
    }


    #[Route('/location', name: 'location', methods:['POST'])]
    public function userLocation(Request $request): Response
    {
        $geolocation = $request->getContent();
       $session = $request->getSession();

        // dd($geolocation);
        // $session->set('geolocation', $geolocation);

        $response = new Response(
            $geolocation,
            Response::HTTP_OK,
            ['content-type' => 'application/json'],
        );

        // $geolocation = $request->request->get('geolocation');

        // dd($geolocation);
        if ($geolocation) {
            $session->set('geolocation', $response);
        }
        // dd($geolocation);
        return $response;
    }

    #[Route(path: '/add/favorite/{id}', name: 'add_favorite')]
    #[IsGranted('ROLE_USER')]
    public function postFavorites(Request $request, StoreRepository $storeRepository, EntityManagerInterface $em, Store $store)
    {
            $storeId = $store->getId();
            $user = $this->getUser();
            $user->addFavourite(
                $storeRepository->find($storeId)
            );
            $em->flush();

        $this->addFlash('success', 'La boutique a été ajouté à vos favoris');
        return $this->redirect($request->headers->get('referer'));
    }

    #[Route('/add/shop-list/{id}', name: 'add_shop-list')]
    #[IsGranted('ROLE_USER')]
    //Add product to list
    public function form(Request $request, EntityManagerInterface $em, ProductRepository $productRepository, Product $product): Response
    {
        $productId = $product->getId();
        $user = $this->getUser();
        $user->addProduct(
            $productRepository->find($productId)
        );

        $em->flush();   

        return $this->redirect($request->headers->get('referer'));
        
    }

}

templates/user/favorite.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Mes favoris - {{ parent() }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user/favorite.css') }}">
{% endblock %}

{% block body %}
    <section class="favorite">
            <h1 class="title-custom marginbt-3">Mes favoris</h1>

            <div class="favorite__container">
            {% if favoritesList %}
                {% for favorite in favoritesList %}
                <div class="favorite-item flex marginbt-1">
                    <div class="img-container">
                        <img src="{{ 'images/uploads/stores/' ~ favorite.picture }}" alt="farm">
                    </div>
                    <div class="details-container">
                        <h4>{{ favorite.name }}</h4>
                {% for address in favorite.addresses %}

                        <p>{{ address.street }}, {{ address.city }}</p>
                        <p>{{ address.zipcode }}</p>
            {% endfor %}

                    </div>
                    <div class="delete flex">
                        <a href="{{ path('user_remove_favorite', {id: favorite.id}) }}"> <i class="fas fa-times"></i></a>
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <p class="none-store">Aucune boutique ajoutée dans vos favoris.</p>
            {% endif %}
            </div>
    </section>

{% endblock %}

templates/user/grocery-list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ma liste de course - {{ parent() }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user/groceries-list.css') }}">
{% endblock %}
{% block body %}
    <div class="container">
        <h2> Ma liste de course</h2>
        <div class="products-container">
            {% if groceryList %}
                {% for product in groceryList %}
                    <div class="product-card">
                        <div class="product_img" style="background-image: url( {{ asset('images/uploads/products/' ~ product.picture ) }})"></div>
                            <span class="bold">
                                {{ product.name }}
                            </span>
                            <div class="price">
                                <h3>
                                    Prix                
                                </h3>
                                <span>
                                    &euro; 
                                    {{ product. price }}
                                    /kg
                                </span>
                            </div>
                            {% for farm in product.stores %}
                                <div class="farm">
                                    <h3>
                                        Ferme
                                    </h3>
                                    <span>
                                        {{ farm.name }}
                                    </span>
                                </div>
                            {% endfor %}
                            <a href="{{ path('user_remove-product', {id: product.id}) }}">
                                <i class="fas fa-times"></i>
                            </a>
                        </div>
                {% endfor %}
                    </div>
            {% else %}
                <h2>
                    Votre liste de course est vide.
                </h2>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Se connecter - {{ parent() }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user/login.css') }}">
{% endblock %}

{% block body %}
    <section class="login">

        <div class=" popup_container-login flex box-shadow">

            <div class="form-img"></div>

            <div class="form-content__container">

                <div class="title-content marginbt-3">
                    <h1>Bienvenue</h1>
                    <p class="sub">chez Loco Loco</p>
                </div>

                <div class="form-content">

                {# --- FORM START --- #}
                    <form method="post">

                        {% if error %}
                            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                        {% endif %}

                        {# Si l'utilisateur est déjà connecté : #}
                        {% if app.user %}
                            <div class="user-already-connected flex marginbt-1">
                                <p class="marginbt-1">
                                    Vous êtes déjà connecté en tant que <br> <span class="bold">{{ app.user.userIdentifier }}</span> 
                                </p>
                                <a href="{{ path('user_logout') }}">
                                    <button class="btn-custom btn-second marginbt-1">
                                        Se déconnecter
                                    </button>    
                                </a>
                                <p class="marginbt-1">----- Ou -----</p>
                                <a href="{{ path('main_index')}}">Retournez sur la page d'accueil</a>
                            </div>
                        {% else %}

                        <div class="inputWithLabel flex">

                            <div class="item">
                                <label class="custom-field" for="inputEmail">
                                    <input class="input-style" type="email" value="{{ lastUsername }}" name="email" id="inputEmail" autocomplete="email" required autofocus>
                                    <span class="placeholder"><i class="far fw fa-envelope"></i> <span class="tiret">-</span> Email *</span>
                                </label>
                            </div>

                            <div class="item">
                                <label class="custom-field" for="inputPassword">
                                    <input class="input-style" type="password" name="password" id="inputPassword" required>
                                    <span class="placeholder"><i class="fas fa-lock"></i> <span class="tiret">-</span> Mot de passe *</span>
                                </label>
                                <a href="#">Mot de passe oublié ?</a>
                            </div>

                            <div class="item">
                                <input type="hidden" name="_csrf_token"
                                value="{{ csrf_token('authenticate') }}">
                            </div>

                            <div class="item">
                                {# On le met ou pas?? #}
                                {# Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                                See https://symfony.com/doc/current/security/remember_me.html

                                <div class="checkbox mb-3">
                                    <label>
                                        <input type="checkbox" name="_remember_me"> Remember me
                                    </label>
                                </div> #}
                            </div>

                        </div>
                
                    
                </div>

                <button type="submit" class="btn btn-second submit flex">
                    Se connecter
                </button>
                {% endif %}
            </form>
                {# --- FORM END --- #}
            </div>
        </div>

    </section>



{% endblock %}

templates/user/profil-client-edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{ parent() }}
    - Modification du profil 
            
        
    {{ user.username }}
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user-profil.css') }}">
    {% endblock %}
    {% block body %}
        <section class="profil">
            <h1 class="title-custom marginbt-1">
                Mon profil

            </h1>
            <div class="content flex">
                <div class="start-client margin ">
                    {% if is_granted('ROLE_PRODUCER') %}
                        <img class="marginbt-1" src="{{ asset('images/avatar/profil-pro.png') }}" alt="avatar">
                    {% else %}
                        <img class="marginbt-1" src="{{ asset('images/avatar/profil-client.png') }}" alt="avatar">
                    {% endif %}
                        <button class="btn btn-second logout" type="submit" form="form" value="Submit">
                            <a href="{{ path('user_logout') }}">
                                Se déconnecter

                            </a>
                        </button>
                    </div>
                    {{ form_start(formEdit) }}
                    <div class="infos margin">
                        <h4>
                            Nom d'utilisateur :        

                        </h4>
                        <div class="text-icon">
                            <p>
                                {{ form_row(formEdit.username, { 'attr': {'class': "span12",
                                'placeholder': user.username} }) }}
                            </p>
                        </div>
                        <h4>
                            Email :  

                        </h4>
                        <div class="text-icon">
                            <p>
                                {{ form_row(formEdit.email, { 'attr': {'class': "span12",
                                    'placeholder': user.email} }) }}
                            </p>
                        </div>
                        <h4>
                            Nom du gérant:
                        </h4>
                        <div class="text-icon">
                            <p>
                                {{ form_row(formEdit.lastname, { 'attr': {'class': "span12",
                                    'placeholder': user.lastname} }) }}
                            </p>
                        </div>

                        <h4>
                            Prénom du gérant:
                        </h4>

                        <div class="text-icon">
                            <p>
                                {{ form_row(formEdit.firstname, { 'attr': {'class': "span12",
                                    'placeholder': user.firstname} }) }}
                            </p>
                        </div>

                        {{ form_end(formEdit) }}
                    </div>
                </div>
            </div>
        </section>
    {% endblock %}
    

templates/user/profil-client.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} - {{ user.username }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user-profil.css') }}">
{% endblock %}

{% block body %}
    <section class="profil">
        <h1 class="title-custom marginbt-1">
            Mon profil utilisateur
        </h1>
        <div class="content flex">
            <div class="start-client margin ">
                <img class="marginbt-1" src="{{ asset('images/avatar/profil-client.png') }}" alt="avatar">
                    {# <p>Modifiez votre avatar ?</p> #}
                <button class="btn btn-second logout" type="submit" form="form" value="Submit">
                    <a href="{{ path('user_logout') }}">
                        Se déconnecter                            
                    </a>
                </button>
            </div>
            <div class="infos margin">
                <a href="{{ path('user_profile-edit') }}" style="font-weight: bold">
                    Modifier le profil
                    <i class="fas fa-edit"></i>
                </a>
                <h4>
                    Nom d'utilisateur :                               
                </h4>
                <div class="text-icon">
                    <p>
                        {{ user.username }}
                    </p>
                </div>
                <h4>
                    Email :                           
                </h4>
                <div class="text-icon">
                    <p>
                        {{ user.email }}
                    </p>
                </div>
                <div class="newsletter-option">
                    <h4>
                        Souhaitez-vous être abonné à notre newsletter ?                             
                    </h4>
                    <i class="fas fa-toggle-off"></i>
                </div>
            </div>
            <div class="end margin">
                <button class="marginbt-1 btn btn-second">
                    <a href="{{ path('user_grocery-list') }}">
                        <i class="fas fa-shopping-basket m-r-1"></i>
                        Voir ma liste de course                            
                    </a>
                </button>
                <button class="marginbt-1 btn btn-second">
                    <a href="{{ path('user_favorite') }}">
                        <i class="fas fa-heart m-r-1"></i>
                            Voir mes favoris                            
                    </a>
                </button>
                <button class="marginbt-1 btn btn-main-outline">
                    <a href="#">
                        Une question ?                              
                        <br>
                            Contactez le support technique                                
                        </a>
                    </button>
                    <button class="btn btn-second">
                        <a href="#">
                            Devenir commerçant                              
                        </a>
                    </button>
                </div>
        </div>
    </section>
{% endblock %}

templates/user/profil-pro.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Profil utilisateur - {{ parent() }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user-profil.css') }}">
{% endblock %}

{% block body %}
<section class="profil">
    <h1 class="title-custom marginbt-1">Mon profil Producteur</h1>

    <div class="content flex">
        <div class="start-pro margin ">
            <img class="marginbt-1" src="{{ asset('images/avatar/profil-pro.png')}}"  alt="avatar">
            {# <p>Modifiez votre avatar ?</p> #}
            <button class="btn btn-second logout" type="submit" form="form" value="Submit">
                <a href="{{ path('user_logout') }}">Se déconnecter</a>
            </button>
        </div>

        <div class="infos margin">
            <a href="{{ path('user_profile-edit') }}" style="font-weight: bold">
                Modifier le profil
                <i class="fas fa-edit"></i>
            </a>

            <h4>Pseudo :</h4>
            <div class="text-icon">
                <p>{{ user.username }}</p>

            </div>

            <h4>Email :</h4>
            <div class="text-icon">
                <p>{{ user.email }}</p>

            </div>

            {% if (app.user.lastname) and  (app.user.firstname) %}
            <h4>Nom et Prénom du gérant:</h4>
            <div class="text-icon">
                <p>{{ user.lastname }} {{ user.firstname }} </p>

            </div>
            {% endif %}
            <div class="newsletter-option">
                <h4>Souhaitez-vous être abonné à notre newsletter ?</h4>
                <i class="fas fa-toggle-off"></i>
            </div>

        </div>
        <div class="end-pro margin">

            <button class="marginbt-1 btn btn-second">
                <a href="{{ path('store_create')}}"><i class="fa-solid fa-plus m-r-1"></i>Ajouter une boutique</a>
            </button>
            <button class="marginbt-1 btn btn-second">
                <a href="{{ path('store_indexpro')}}"><i class="fas fa-store m-r-1"></i>Gérer mes boutiques</a>
            </button>
            <button class="marginbt-1 btn btn-main-outline">
                <a href="#" >Une question ? <br> Contactez le support technique</a>
            </button>

            </div>  
        </div>

    </div>
</section>

{% endblock %}